# Generated by Django 4.2.2 on 2023-06-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LenguajeProgra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
    ]
