# Generated by Django 4.2.2 on 2023-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0002_lenguajeprogra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programador',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='programador',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='programador',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
