# Generated by Django 4.2.2 on 2023-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0003_alter_programador_edad_alter_programador_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=40)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
    ]
