# Generated by Django 4.2.2 on 2023-06-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0004_nuevopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevopedido',
            name='tiempo',
            field=models.TimeField(null=True),
        ),
    ]
